### PR TITLE
Issue/124/mask summarizers

### PR DESCRIPTION
**Pull request by eacharles**
## Code Quality
- [ ] My code follows [the code style of this project](https://rail-hub.readthedocs.io/en/latest/source/contributing.html#naming-conventions)
- [ ] I have written unit tests or justified all instances of `#pragma: no cover`; in the case of a bugfix, a new test that breaks as a result of the bug has been added
- [ ] My code contains relevant comments and necessary documentation for future maintainers; the change is reflected in applicable demos/tutorials (with output cleared!) and added/updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] Any breaking changes, described above, are accompanied by backwards compatibility and deprecation warnings

### CODE REVIEW

**Comment by eacharles** [comment]
Still need to add tests

**Comment by eacharles** [comment]
#124

**Comment by ztq1996** [comment]
I think what is implemented is a good starting point. 

One thing I want to suggest: usually when tomographic binning is provided, people want to get the n(z) for **all** the bins. So we probably want something that produces multiple n(z) as the default. The difficult thing about this is the data structure, since ceci wants a deterministic output path, I am thinking about creating a "nzHandle" with a list of qp ensembles as its data, does that make sense?

**Comment by eacharles** [comment]
I had a similar idea, The main difference was that I was thinking to just put them all in a single qp Ensemble and use the ancillary data to provide information about the bin...

**Review by ztq1996 — APPROVED** [review]

**Pull request merged**
